### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'projects.find')

### ISSUE THREAD

**Issue by stanlyliusu** [benhughes/of-start-toggl-timer#2]
I'm trying your script. But I encounter this issue : TypeError: undefined is not an object (evaluating 'projects.find') 

Could you please help me to identify the reason? 

Thanks,

Stanley

**Comment by benhughes** [comment]
Hey Stanley, I believe someone else run into this issue and fixed it by creating at least one project in Toggl, can you try that and let me know if it fixes it? Will add a proper fix when I get the chance.

**Comment by benhughes** [comment]
Should be fixed with this release: https://github.com/benhughes/OmniToggl/releases/tag/1.1.1
Please comment if you are still running into this issue. Thanks for reporting
