### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new URL.FetchRequest()')

### ISSUE THREAD

**Issue by abnerSK** [benhughes/of-start-toggl-timer#3]
![image](https://user-images.githubusercontent.com/27146110/107824326-913f8500-6d81-11eb-97e7-44f077ce2107.png)

I have double checked that My Toggl already has projects created and several actions logged(not with OmniToggl).

Could you look into it or suggest me any method to debug? Thanks a lot.

**Comment by benhughes** [comment]
Hey @jory18, what version of OmniFocus are you on. That error sounds like it's using an old version of OmniFocus. This plugin needs at least 3.11.2.

**Comment by abnerSK** [comment]
I updated OmniFocus from 3.11.0 to 3.11.2, and now the error got fixed and the plugin works very well.

Thanks very much!
