### ISSUE TITLE
Unable to find the script "common.js".

### ISSUE THREAD

**Issue by shuaiwang88** [benhughes/of-start-toggl-timer#7]
the window popped up with "Error loading plug-in. Unable to find the script "common.js" after I clicked the OmniToggl.omnifocusjs button. I am using M1 MacBook Air.

**Comment by benhughes** [comment]
Hey there, Thanks for the report 

Just to confirm, how did you install it? from https://github.com/benhughes/OmniToggl/releases?

**Comment by shuaiwang88** [comment]
> Hey there, Thanks for the report
> 
> Just to confirm, how did you install it? from https://github.com/benhughes/OmniToggl/releases?

Oh, bummer. I copied the whole repo..Solved! Thanks!

**Comment by shuaiwang88** [comment]
Hi, are you interested in writing a similar plugin for Clockify?  The reason is Toggl does not support task within the project.

**Comment by benhughes** [comment]
what do you mean by tasks? Does an individual timer not represent a task within a project?
